version: "3.9"

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: search
      MYSQL_USER: search
      MYSQL_PASSWORD: search
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      LANG: ja_JP.UTF-8
      LANGUAGE: ja_JP:ja
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

